### ISSUE TITLE
Using a Converter with a PojoTable Fails

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/lsql#15]
- Code fails in the first line, claiming that uploadActive in AutoJob has the wrong type.
- 2nd line, assigning the Converter is never executed

```
table = this.lSql.table("tAutoJob", AutoJob.class);
table.getTable().column("uploadActive").setConverter(new AutoJobBooleanConverter());

```
```

Caused by: java.lang.IllegalArgumentException: Field ....AutoJob#uploadActive has the wrong type: 'boolean'. Expected: 'java.lang.String'
	at com.w11k.lsql.PojoMapper.checkConformity(PojoMapper.java:124) ~[lsql-core-0.21.8.jar:na]
	at com.w11k.lsql.PojoTable.<init>(PojoTable.java:27) ~[lsql-core-0.21.8.jar:na]
	at com.w11k.lsqtable(LSql.java:172) ~[lsql-core-0.21.8.jar:na]
	at....AutoJobDao.<init>(AutoJobDao.java:42) ~[main/:na]
```

**Comment by romanroe** [comment]
Release 0.21.9 provides a new API to simplify this use case.

```
table = this.lSql.table("tAutoJob")
    .setColumnConverter("uploadActive", new AutoJobBooleanConverter())
    ....
    .withPojo(AutoJob.class);

```
