### ISSUE TITLE
Exception in PojoMapper

### ISSUE THREAD

**Issue by pburgmer** [w11k/lsql#31]
Not always but sometimes the PojoMapper throws an IllegalAccessException. After server restart it works for a while but the exception started to appear again.

Unfortunately there is no information about the field name.

Lombok's Data annotation adds getter and setter methods for all fields. RequiredArgsConstructor in this case adds a constructor without parameters.

```
java.lang.IllegalAccessException: Class com.w11k.lsql.PojoMapper can not access a member of class xyz.ABC with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[?:1.8.0_40]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[?:1.8.0_40]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:490) ~[?:1.8.0_40]
	at com.w11k.lsql.PojoMapper.setValue(PojoMapper.java:70) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.PojoQuery.setValue(PojoQuery.java:41) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.AbstractQuery.extractEntity(AbstractQuery.java:282) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.AbstractQuery.access$000(AbstractQuery.java:29) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.AbstractQuery$2.call(AbstractQuery.java:136) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.AbstractQuery$2.call(AbstractQuery.java:133) ~[lsql-core-0.28.7.jar:?]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54) ~[rxjava-1.0.16.jar:1.0.16]
	at com.w11k.lsql.query.AbstractQuery$3.call(AbstractQuery.java:158) ~[lsql-core-0.28.7.jar:?]
	at com.w11k.lsql.query.AbstractQuery$3.call(AbstractQuery.java:150) ~[lsql-core-0.28.7.jar:?]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable.subscribe(Observable.java:8264) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.Observable.subscribe(Observable.java:8231) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433) ~[rxjava-1.0.16.jar:1.0.16]
	at rx.observables.BlockingObservable.first(BlockingObservable.java:160) ~[rxjava-1.0.16.jar:1.0.16]
	at com.w11k.lsql.query.AbstractQuery.toList(AbstractQuery.java:96) ~[lsql-core-0.28.7.jar:?]
```

```
package xyz;

import com................Month;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@RequiredArgsConstructor
class ABC {
	
	public Month timeId;
	public String saStatus;
        public Date dueDate;

}
```

**Comment by romanroe** [comment]
field name gets logged in version 0.30.1
